features: ['mean', 'std', 'min', 'max']
sensors: ['accelerometer', 'gyroscope', 'linear_acceleration', 'magnetic_field']
transport_modes:
  bus: 0
  car: 1
  train: 2
window_next_step_seconds: 5
window_size_seconds: 10
